<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Biletix.Application\Biletix.Application.csproj" />
    <ProjectReference Include="..\Biletix.Domain\Biletix.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Elasticsearch" Version="8.*" />
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="8.*" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="8.*" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.*" />
    <PackageReference Include="Confluent.Kafka" Version="2.*" />
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.*" />
    <PackageReference Include="MediatR" Version="12.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.*" />
    <PackageReference Include="StackExchange.Redis" Version="2.*" />
    <PackageReference Include="Stripe.net" Version="45.*" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.*" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
